<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup Label="EF Core — verzije MORAJU biti uskladjene sa Npgsql provajderom">
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.4" />
  </ItemGroup>

  <ItemGroup Label="Otpornost i DI">
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="10.9.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup Label="Testiranje">
    <PackageVersion Include="xunit.v3.mtp-v2" Version="4.0.0" />
    <PackageVersion Include="Testcontainers.PostgreSql" Version="4.14.0" />
  </ItemGroup>

  <ItemGroup Label="Redis">
    <PackageVersion Include="StackExchange.Redis" Version="3.1.31" />
    <PackageVersion Include="Testcontainers.Redis" Version="4.14.0" />
  </ItemGroup>

    <ItemGroup Label="Health checks">
    <PackageVersion Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0" />
    <PackageVersion Include="AspNetCore.HealthChecks.Redis" Version="9.0.0" />
  </ItemGroup>
</Project>