// <auto-generated />
using System;
using FxRateService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FxRateService.Infrastructure.Migrations
{
    [DbContext(typeof(FxDbContext))]
    partial class FxDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FxRateService.Infrastructure.Persistence.ExchangeRateRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("AsOf")
                        .HasColumnType("date")
                        .HasColumnName("as_of");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("base_currency")
                        .IsFixedLength();

                    b.Property<string>("QuoteCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("quote_currency")
                        .IsFixedLength();

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("rate");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("retrieved_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("AsOf", "BaseCurrency", "QuoteCurrency", "Source")
                        .IsUnique()
                        .HasDatabaseName("ux_exchange_rates_day_pair_source");

                    b.HasIndex("BaseCurrency", "QuoteCurrency", "Source", "AsOf")
                        .HasDatabaseName("ix_exchange_rates_history");

                    b.ToTable("exchange_rates", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
